#pragma once
#include "high_order_quadrature.hpp"
#include "high_order_primitives.hpp"
#include <ipc/high_order_contact/high_order_contact_parameters.hpp>
#include <ipc/math/math.hpp>
#include <ipc/distance/point_point.hpp>
#include <ipc/distance/point_edge.hpp>

// ----------------------------------------------------
namespace alternating_contact_potential {
    constexpr double threshold0 = 1e-12;
    using namespace ipc;

    // generated by sympy
    /// @brief Compute the barrier potential value.
    /// @param d The distance.
    /// @param params The contact parameters.
    /// @return The barrier potential value.
    double barrier(
        const double d,
        const HighOrderContactParameters& params
    ) {
        const double eps = params.dhat;
        const double p = params.r;
        if (d <= threshold0) return (0);
        const double x0 = std::pow(eps, 3);
        const double x1 = std::pow(d, -p)/x0;
        const double x2 = d/eps;
        return ((x2 < 1.0/2.0) ? (
        (4.0/3.0)*x1*(6*std::pow(d, 3) - 6*std::pow(d, 2)*eps + x0)
        )
        : ((x2 < 1) ? (
        -8.0/3.0*x1*std::pow(d - eps, 3)
        )
        : (
        0
        )));
    }

    // generated by sympy
    /// @brief Compute the first derivative of the barrier potential.
    /// @param d The distance.
    /// @param params The contact parameters.
    /// @return The first derivative of the barrier potential.
    double barrier_d(
        const double d,
        const HighOrderContactParameters& params
    ) {
        const double eps = params.dhat;
        const double p = params.r;
        if (d <= threshold0) return (0);
        const double x0 = std::pow(eps, 3);
        const double x1 = 1.0/x0;
        const double x2 = std::pow(d, p + 1);
        const double x3 = std::pow(d, 3);
        const double x4 = std::pow(d, 2);
        const double x5 = d/eps;
        const double x6 = d - eps;
        return ((x5 < 1.0/2.0) ? (
        (4.0/3.0)*x1*(6*eps*p*x4 - 12*eps*x4 - p*x0 - 6*p*x3 + 18*x3)/x2
        )
        : ((x5 < 1) ? (
        (8.0/3.0)*std::pow(d, -2*p - 1)*x1*std::pow(x6, 2)*(std::pow(d, p)*p*x6 - 3*x2)
        )
        : (
        0
        )));
    }

    // generated by sympy
    /// @brief Compute the second derivative of the barrier potential.
    /// @param d The distance.
    /// @param params The contact parameters.
    /// @return The second derivative of the barrier potential.
    double barrier_dd(
        const double d,
        const HighOrderContactParameters& params
    ) {
        const double eps = params.dhat;
        const double p = params.r;
        if (d <= threshold0) return (0);
        const double x0 = 3*d;
        const double x1 = -eps;
        const double x2 = 2*p;
        const double x3 = std::pow(d, x2 + 3);
        const double x4 = 12*x3;
        const double x5 = std::pow(eps, 3);
        const double x6 = std::pow(d, x2 + 1)*p*(p + 1);
        const double x7 = std::pow(d, -3*p - 3)/x5;
        const double x8 = d/eps;
        const double x9 = d + x1;
        return ((x8 < 1.0/2.0) ? (
        (4.0/3.0)*x7*(-p*x4*(-2*eps + x0) + x4*(x0 + x1) + x6*(6*std::pow(d, 3) - 6*std::pow(d, 2)*eps + x5))
        )
        : ((x8 < 1) ? (
        (8.0/3.0)*x7*(6*std::pow(d, x2 + 2)*p*std::pow(x9, 2) - 6*x3*x9 - x6*std::pow(x9, 3))
        )
        : (
        0
        )));
    }

    /// @brief Compute the integrated potential over an edge.
    /// @param e0 The first vertex of the edge.
    /// @param e1 The second vertex of the edge.
    /// @param params The contact parameters.
    /// @param dist_sq_function A function that computes the squared distance from a point on the edge to the other primitive.
    /// @param integration_area The length of the edge (optional, computed if negative).
    /// @return The integrated potential.
    template<typename F>
    double potential(
        const Eigen::Vector2d e0,
        const Eigen::Vector2d e1,
        const HighOrderContactParameters& params,
        F &&dist_sq_function,
        const double integration_area = -1.0
    ) {
        GaussLobatto::Rule rule = GaussLobatto::get_rule(params.quad_order);
        double integral = 0.0;
        const Eigen::Vector2d e1pe0 = (e1 + e0) * 0.5;
        const Eigen::Vector2d e1me0 = (e1 - e0) * 0.5;
        for (const auto &qw : rule) {
            const double sample = barrier(sqrt(dist_sq_function(e1pe0 + qw.first * e1me0)), params);
            integral += sample * qw.second;
        }
        const double length = (integration_area < 0) ? ((e0 - e1).norm()) : integration_area;
        return 0.5 * length * integral;
    }

    /// @brief Compute the gradient of the integrated potential over an edge.
    /// @param e0 The first vertex of the edge.
    /// @param e1 The second vertex of the edge.
    /// @param params The contact parameters.
    /// @param dist_sq_function A function that computes the squared distance from a point on the edge to the other primitive.
    /// @param dist_sq_gradient A function that computes the gradient of the squared distance.
    /// @param integration_area The length of the edge (optional, computed if negative).
    /// @return The gradient of the integrated potential.
    template<typename R, typename F, typename Fd>
    R gradient(
        const Eigen::Vector2d e0,
        const Eigen::Vector2d e1,
        const HighOrderContactParameters& params,
        F &&dist_sq_function,
        Fd &&dist_sq_gradient,
        const double integration_area = -1.0
    ) {
        GaussLobatto::Rule rule = GaussLobatto::get_rule(params.quad_order);
        R global = R::Zero();
        const Eigen::Vector2d e1pe0 = (e1 + e0) * 0.5;
        const Eigen::Vector2d e1me0 = (e1 - e0) * 0.5;
        for (const auto &qw : rule) {
            const Eigen::Vector2d q = e1pe0 + qw.first * e1me0;
            const double d2 = dist_sq_function(q);

            if (d2 <= 1e-16) continue;

            const double d = sqrt(d2);
            const auto g = dist_sq_gradient(q);
            const double local_val = barrier_d(d, params) * 0.5 / d * qw.second;

            const double t = (qw.first + 1.0) * 0.5;

            // Distribute the first 2 components (gradient wrt q) to e0 and e1
            global.head(2) += g.head(2) * (1.0 - t) * local_val;
            global.segment(2, 2) += g.head(2) * t * local_val;

            // Accumulate the rest
            global.tail(global.size() - 4) += g.tail(g.size() - 2) * local_val;
        }
        const double length = (integration_area < 0) ? ((e0 - e1).norm()) : integration_area;
        return 0.5 * length * global;
    }

    /// @brief Compute the Hessian of the integrated potential over an edge.
    /// @param e0 The first vertex of the edge.
    /// @param e1 The second vertex of the edge.
    /// @param params The contact parameters.
    /// @param dist_sq_function A function that computes the squared distance from a point on the edge to the other primitive.
    /// @param dist_sq_gradient A function that computes the gradient of the squared distance.
    /// @param dist_sq_hessian A function that computes the Hessian of the squared distance.
    /// @param integration_area The length of the edge (optional, computed if negative).
    /// @return The Hessian of the integrated potential.
    template<typename R, typename F, typename Fd, typename Fdd>
    R hessian(
        const Eigen::Vector2d e0,
        const Eigen::Vector2d e1,
        const HighOrderContactParameters& params,
        F &&dist_sq_function,
        Fd &&dist_sq_gradient,
        Fdd &&dist_sq_hessian,
        const double integration_area = -1.0
    ) {
        GaussLobatto::Rule rule = GaussLobatto::get_rule(params.quad_order);
        R global = R::Zero();
        const Eigen::Vector2d e1pe0 = (e1 + e0) * 0.5;
        const Eigen::Vector2d e1me0 = (e1 - e0) * 0.5;
        for (const auto &qw : rule) {
            const Eigen::Vector2d q = e1pe0 + qw.first * e1me0;
            const double d2 = dist_sq_function(q);

            if (d2 <= 1e-16) continue;

            const double d = sqrt(d2);
            const double b_d = barrier_d(d, params);
            const double b_dd = barrier_dd(d, params);

            const auto g_raw = dist_sq_gradient(q);
            const auto H_raw = dist_sq_hessian(q);

            // Chain rule for B(sqrt(d2))
            // grad f = (B'/2d) * g
            // hess f = (B'/2d) * H + (B''/4d^2 - B'/4d^3) * g * g^T
            const double c1 = b_d / (2.0 * d);
            const double c2 = (b_dd * d - b_d) / (4.0 * d * d * d);

            const double w = qw.second;
            const double t = (qw.first + 1.0) * 0.5;
            const double t0 = 1.0 - t;
            const double t1 = t;

            const int dim_local = g_raw.size();

            for (int i = 0; i < dim_local; ++i) {
                for (int j = 0; j < dim_local; ++j) {
                    const double val = (c1 * H_raw(i, j) + c2 * g_raw(i) * g_raw(j)) * w;

                    if (i < 2) {
                        if (j < 2) {
                            global(i, j) += val * t0 * t0;
                            global(i, j + 2) += val * t0 * t1;
                            global(i + 2, j) += val * t1 * t0;
                            global(i + 2, j + 2) += val * t1 * t1;
                        } else {
                            global(i, j + 2) += val * t0;
                            global(i + 2, j + 2) += val * t1;
                        }
                    } else {
                        if (j < 2) {
                            global(i + 2, j) += val * t0;
                            global(i + 2, j + 2) += val * t1;
                        } else {
                            global(i + 2, j + 2) += val;
                        }
                    }
                }
            }
        }
        const double length = (integration_area < 0) ? ((e0 - e1).norm()) : integration_area;
        return 0.5 * length * global;
    }

    using EV2GradType = Eigen::Vector<double, 6>;
    using EV2HessType = Eigen::Matrix<double, 6, 6>;
    using EE2GradType = Eigen::Vector<double, 8>;
    using EE2HessType = Eigen::Matrix<double, 8, 8>;
 
    /// @brief Compute the potential for a 2D edge-vertex collision.
    /// @param positions The positions of the edge vertices and the vertex.
    /// @param params The contact parameters.
    /// @param integration_area The length of the edge (optional).
    /// @return The potential value.
    double potential_EV(
        Eigen::ConstRef<VectorMax<double, HighOrderCollision::ELEMENT_SIZE>> positions,
        const HighOrderContactParameters& params,
        const double integration_area = -1.0
    )
    {
        const Eigen::Matrix<double, 3, 2> all_pos = slice_positions<double, 3, 2>(positions);
        const Eigen::Vector2d e0 = all_pos.row(0);
        const Eigen::Vector2d e1 = all_pos.row(1);
        const Eigen::Vector2d v0 = all_pos.row(2);

        return potential(
            e0, e1, params,
            [&v0](const Eigen::Vector2d &p) { return point_point_distance(p, v0); },
            integration_area
        );
    }

    /// @brief Compute the gradient of the potential for a 2D edge-vertex collision.
    /// @param positions The positions of the edge vertices and the vertex.
    /// @param params The contact parameters.
    /// @param integration_area The length of the edge (optional).
    /// @return The gradient vector.
    EV2GradType gradient_EV(
        Eigen::ConstRef<VectorMax<double, HighOrderCollision::ELEMENT_SIZE>> positions,
        const HighOrderContactParameters& params,
        const double integration_area = -1.0
    )
    {
        const Eigen::Matrix<double, 3, 2> all_pos = slice_positions<double, 3, 2>(positions);
        const Eigen::Vector2d e0 = all_pos.row(0);
        const Eigen::Vector2d e1 = all_pos.row(1);
        const Eigen::Vector2d v0 = all_pos.row(2);

        return gradient<EV2GradType>(
            e0, e1, params,
            [&v0](const Eigen::Vector2d &p) { return point_point_distance(p, v0); },
            [&v0](const Eigen::Vector2d &p) { return point_point_distance_gradient(p, v0); },
            integration_area
        );
    }

    /// @brief Compute the Hessian of the potential for a 2D edge-vertex collision.
    /// @param positions The positions of the edge vertices and the vertex.
    /// @param params The contact parameters.
    /// @param integration_area The length of the edge (optional).
    /// @return The Hessian matrix.
    EV2HessType hessian_EV(
        Eigen::ConstRef<VectorMax<double, HighOrderCollision::ELEMENT_SIZE>> positions,
        const HighOrderContactParameters& params,
        const double integration_area = -1.0
    )
    {
        const Eigen::Matrix<double, 3, 2> all_pos = slice_positions<double, 3, 2>(positions);
        const Eigen::Vector2d e0 = all_pos.row(0);
        const Eigen::Vector2d e1 = all_pos.row(1);
        const Eigen::Vector2d v0 = all_pos.row(2);

        return hessian<EV2HessType>(
            e0, e1, params,
            [&v0](const Eigen::Vector2d &p) { return point_point_distance(p, v0); },
            [&v0](const Eigen::Vector2d &p) { return point_point_distance_gradient(p, v0); },
            [&v0](const Eigen::Vector2d &p) { return point_point_distance_hessian(p, v0); },
            integration_area
        );
    }

    /// @brief Compute the potential for a 2D edge-edge collision.
    /// @param positions The positions of the two edges.
    /// @param params The contact parameters.
    /// @param integration_area The length of the first edge (optional).
    /// @return The potential value.
    double potential_EE(
        Eigen::ConstRef<VectorMax<double, HighOrderCollision::ELEMENT_SIZE>> positions,
        const HighOrderContactParameters& params,
        const double integration_area = -1.0
    ) {
        const Eigen::Matrix<double, 4, 2> all_pos = slice_positions<double, 4, 2>(positions);
        const Eigen::Vector2d e0 = all_pos.row(0);
        const Eigen::Vector2d e1 = all_pos.row(1);
        const Eigen::Vector2d other0 = all_pos.row(2);
        const Eigen::Vector2d other1 = all_pos.row(3);

        return potential(
            e0, e1, params,
            [&other0, &other1](const Eigen::Vector2d &p) { return point_edge_distance(p, other0, other1); },
            integration_area
        );
    }

    /// @brief Compute the gradient of the potential for a 2D edge-edge collision.
    /// @param positions The positions of the two edges.
    /// @param params The contact parameters.
    /// @param integration_area The length of the first edge (optional).
    /// @return The gradient vector.
    EE2GradType gradient_EE(
        Eigen::ConstRef<VectorMax<double, HighOrderCollision::ELEMENT_SIZE>> positions,
        const HighOrderContactParameters& params,
        const double integration_area = -1.0
    ) {
        const Eigen::Matrix<double, 4, 2> all_pos = slice_positions<double, 4, 2>(positions);
        const Eigen::Vector2d e0 = all_pos.row(0);
        const Eigen::Vector2d e1 = all_pos.row(1);
        const Eigen::Vector2d other0 = all_pos.row(2);
        const Eigen::Vector2d other1 = all_pos.row(3);

        return gradient<EE2GradType>(
            e0, e1, params,
            [&other0, &other1](const Eigen::Vector2d &p) { return point_edge_distance(p, other0, other1); },
            [&other0, &other1](const Eigen::Vector2d &p) { return point_edge_distance_gradient(p, other0, other1); },
            integration_area
        );
    }

    /// @brief Compute the Hessian of the potential for a 2D edge-edge collision.
    /// @param positions The positions of the two edges.
    /// @param params The contact parameters.
    /// @param integration_area The length of the first edge (optional).
    /// @return The Hessian matrix.
    EE2HessType hessian_EE(
        Eigen::ConstRef<VectorMax<double, HighOrderCollision::ELEMENT_SIZE>> positions,
        const HighOrderContactParameters& params,
        const double integration_area = -1.0
    ) {
        const Eigen::Matrix<double, 4, 2> all_pos = slice_positions<double, 4, 2>(positions);
        const Eigen::Vector2d e0 = all_pos.row(0);
        const Eigen::Vector2d e1 = all_pos.row(1);
        const Eigen::Vector2d other0 = all_pos.row(2);
        const Eigen::Vector2d other1 = all_pos.row(3);

        return hessian<EE2HessType>(
            e0, e1, params,
            [&other0, &other1](const Eigen::Vector2d &p) { return point_edge_distance(p, other0, other1); },
            [&other0, &other1](const Eigen::Vector2d &p) { return point_edge_distance_gradient(p, other0, other1); },
            [&other0, &other1](const Eigen::Vector2d &p) { return point_edge_distance_hessian(p, other0, other1); },
            integration_area
        );
    }
} // namespace alternating_contact_potential